"""empty message

Revision ID: 7a7d8ecd8821
Revises: 68bd3ee99668
Create Date: 2025-03-29 11:44:06.887882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7d8ecd8821'
down_revision = '68bd3ee99668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_group', schema=None) as batch_op:
        batch_op.drop_column('special_type')

    # ### end Alembic commands ###
