"""empty message

Revision ID: 9f9818e66332
Revises: 1c7a6f6aadc0
Create Date: 2025-03-28 23:26:02.016710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9818e66332'
down_revision = '1c7a6f6aadc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wrong_answer')
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_column('marked')

    op.create_table('wrong_answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('wrong_count', sa.INTEGER(), nullable=True),
    sa.Column('last_wrong_time', sa.DATETIME(), nullable=True),
    sa.Column('cleared', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['word_group.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
