"""Initial migration

Revision ID: db0dcee9793f
Revises: 
Create Date: 2025-03-27 12:28:59.402832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0dcee9793f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('study_count', sa.Integer(), nullable=True),
    sa.Column('order_quiz_count', sa.Integer(), nullable=True),
    sa.Column('random_quiz_count', sa.Integer(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('random_last_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['word_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.String(length=100), nullable=False),
    sa.Column('chinese', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['word_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('group_stats')
    op.drop_table('word_group')
    # ### end Alembic commands ###
