"""empty message

Revision ID: f73e39aa1c47
Revises: 9f9818e66332
Create Date: 2025-03-29 00:20:01.088485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73e39aa1c47'
down_revision = '9f9818e66332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletion_mark', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_column('deletion_mark')

    # ### end Alembic commands ###
